version: '3.8'

services:
  mysqldb:
    image: mysql:lts
    container_name: myslq-sicat
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb-sicat
    ports:
      - "3308:27017"
    volumes:
      - api_mongodb-data:/data/db

volumes:
  mysql-data:
    external: true
  api_mongodb-data: # Corrección del nombre del volumen
    external: true

# Asegúrate de que el volumen se cree y se maneje por Docker Compose
